/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Function.*;
import Main.EditField;
import Main.PreviewIMG;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Someone-PC
 */
public class EditFieldView extends javax.swing.JFrame {

    /**
     * Creates new form EditFieldView
     */
    public EditFieldView() {
        initComponents();
    }
    
    public EditFieldView(int[][] r, int[][] g, int[][] b, int[][] Gray) {
        this.R = r;
        this.G = g;
        this.B = b;
        this.Gray = Gray;
        this.R1 = r;
        this.G1 = g;
        this.B1 = b;        
        this.Gray1 = Gray;
        
        this.rotateR = 0;
        this.moveR = 0;        
        this.segmented = false;
        
        this.originalRGB = new PreviewIMG(this.R, this.G, this.B);
        this.originalGray = new PreviewIMG(this.Gray);
        
        initComponents();
        
        this.valSegTres.setValue(200);
        this.valDir.setText("img");
    }
    
    public void imgTresholdRun(){
        int val = (int)this.valSegTres.getValue();
        this.R1 = SegTreshold.threshold(this.R1, val);
        this.G1 = SegTreshold.threshold(this.G1, val);
        this.B1 = SegTreshold.threshold(this.B1, val);
        this.Gray1 = SegTreshold.threshold(this.Gray1, val);
        this.segmented = true;
    }
    
    public void imgDilation(){
        this.R1 = dilasi.DilasiRes(this.R1);
        this.G1 = dilasi.DilasiRes(this.G1);
        this.B1 = dilasi.DilasiRes(this.B1);
        this.Gray1 = dilasi.DilasiRes(this.Gray1);
    }
    
    public void imgErosion(){
        this.R1 = erosi.ErosiRes(this.R1);
        this.G1 = erosi.ErosiRes(this.G1);
        this.B1 = erosi.ErosiRes(this.B1);
        this.Gray1 = erosi.ErosiRes(this.Gray1);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frGeser = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        valGeser = new javax.swing.JSpinner();
        btAtas = new javax.swing.JButton();
        btKanan = new javax.swing.JButton();
        btBawah = new javax.swing.JButton();
        btKiri = new javax.swing.JButton();
        btGeserBack = new javax.swing.JButton();
        frZoom = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btZoomIn = new javax.swing.JButton();
        btZoomOut = new javax.swing.JButton();
        btZoomBack = new javax.swing.JButton();
        frRotate = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btRotateCW = new javax.swing.JButton();
        valRotate = new javax.swing.JSpinner();
        btRotateCCW = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btRotateBack = new javax.swing.JButton();
        frBrightness = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valBrightness = new javax.swing.JSpinner();
        btBrightnessInc = new javax.swing.JButton();
        btBrightnessDec = new javax.swing.JButton();
        btBrightnessMult = new javax.swing.JButton();
        btBrightnessDivd = new javax.swing.JButton();
        btBrightBack = new javax.swing.JButton();
        frKonvolusi = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btConvSharpen = new javax.swing.JButton();
        btConvEdge = new javax.swing.JButton();
        btConvBack = new javax.swing.JButton();
        frMorphology = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btMorpDilation = new javax.swing.JButton();
        btMorpErotion = new javax.swing.JButton();
        btClosing = new javax.swing.JButton();
        btOpening = new javax.swing.JButton();
        btMorpBack = new javax.swing.JButton();
        frSegment = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btSegmenTres = new javax.swing.JButton();
        valSegTres = new javax.swing.JSpinner();
        btSegBack = new javax.swing.JButton();
        frSmoothing = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btSmoothMean = new javax.swing.JButton();
        btSmoothModus = new javax.swing.JButton();
        btSmoothMedia = new javax.swing.JButton();
        btSmoothBack = new javax.swing.JButton();
        frSave = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btSaveLossy = new javax.swing.JButton();
        btSaveLossless = new javax.swing.JButton();
        valDir = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btSaveBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fitur = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btPreviewRGB = new javax.swing.JButton();
        btPreviewGray = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btOriginalRGB = new javax.swing.JButton();
        btOriginalGray = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btHistogram = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btGeser = new javax.swing.JButton();
        btZoom = new javax.swing.JButton();
        btRotate = new javax.swing.JButton();
        btBrightness = new javax.swing.JButton();
        btConvolution = new javax.swing.JButton();
        btMorphology = new javax.swing.JButton();
        btSegment = new javax.swing.JButton();
        btSmoothing = new javax.swing.JButton();

        jLabel1.setText("Move");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("px");

        btAtas.setText("Up");
        btAtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtasActionPerformed(evt);
            }
        });

        btKanan.setText("Right");
        btKanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKananActionPerformed(evt);
            }
        });

        btBawah.setText("Down");
        btBawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBawahActionPerformed(evt);
            }
        });

        btKiri.setText("Left");
        btKiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKiriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btKiri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAtas)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(valGeser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btKanan))
                    .addComponent(btBawah))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAtas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valGeser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKanan)
                    .addComponent(btKiri)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBawah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btGeserBack.setText("Back");
        btGeserBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeserBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frGeserLayout = new javax.swing.GroupLayout(frGeser.getContentPane());
        frGeser.getContentPane().setLayout(frGeserLayout);
        frGeserLayout.setHorizontalGroup(
            frGeserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frGeserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frGeserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frGeserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGeserBack)
                .addContainerGap())
        );
        frGeserLayout.setVerticalGroup(
            frGeserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frGeserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGeserBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Zoom");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btZoomIn.setText("Zoom In");
        btZoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomInActionPerformed(evt);
            }
        });

        btZoomOut.setText("Zoom Out");
        btZoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btZoomIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btZoomOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btZoomOut)
                    .addComponent(btZoomIn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btZoomBack.setText("Back");
        btZoomBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frZoomLayout = new javax.swing.GroupLayout(frZoom.getContentPane());
        frZoom.getContentPane().setLayout(frZoomLayout);
        frZoomLayout.setHorizontalGroup(
            frZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frZoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frZoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btZoomBack)
                .addContainerGap())
        );
        frZoomLayout.setVerticalGroup(
            frZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frZoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZoomBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Rotate");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btRotateCW.setText("CW");
        btRotateCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotateCWActionPerformed(evt);
            }
        });

        btRotateCCW.setText("CCW");
        btRotateCCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotateCCWActionPerformed(evt);
            }
        });

        jLabel7.setText("Degrees");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRotateCW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valRotate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRotateCCW)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRotateCW)
                    .addComponent(valRotate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRotateCCW)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btRotateBack.setText("Back");
        btRotateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotateBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frRotateLayout = new javax.swing.GroupLayout(frRotate.getContentPane());
        frRotate.getContentPane().setLayout(frRotateLayout);
        frRotateLayout.setHorizontalGroup(
            frRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frRotateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frRotateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRotateBack)
                .addContainerGap())
        );
        frRotateLayout.setVerticalGroup(
            frRotateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frRotateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRotateBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Brightness");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Value");

        btBrightnessInc.setText("Increase");
        btBrightnessInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightnessIncActionPerformed(evt);
            }
        });

        btBrightnessDec.setText("Decrease");
        btBrightnessDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightnessDecActionPerformed(evt);
            }
        });

        btBrightnessMult.setText("Multiple");
        btBrightnessMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightnessMultActionPerformed(evt);
            }
        });

        btBrightnessDivd.setText("Divide");
        btBrightnessDivd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightnessDivdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valBrightness, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btBrightnessDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBrightnessInc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBrightnessMult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBrightnessDivd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(valBrightness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBrightnessInc)
                    .addComponent(btBrightnessMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBrightnessDec)
                    .addComponent(btBrightnessDivd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btBrightBack.setText("Back");
        btBrightBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frBrightnessLayout = new javax.swing.GroupLayout(frBrightness.getContentPane());
        frBrightness.getContentPane().setLayout(frBrightnessLayout);
        frBrightnessLayout.setHorizontalGroup(
            frBrightnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frBrightnessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frBrightnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frBrightnessLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBrightBack)
                .addContainerGap())
        );
        frBrightnessLayout.setVerticalGroup(
            frBrightnessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frBrightnessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBrightBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Konvolusi");

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Choose kernel");

        btConvSharpen.setText("Sharpen");
        btConvSharpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvSharpenActionPerformed(evt);
            }
        });

        btConvEdge.setText("Edge Detect");
        btConvEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvEdgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(btConvEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConvSharpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConvSharpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConvEdge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConvBack.setText("Back");
        btConvBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frKonvolusiLayout = new javax.swing.GroupLayout(frKonvolusi.getContentPane());
        frKonvolusi.getContentPane().setLayout(frKonvolusiLayout);
        frKonvolusiLayout.setHorizontalGroup(
            frKonvolusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frKonvolusiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frKonvolusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frKonvolusiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConvBack)
                .addContainerGap())
        );
        frKonvolusiLayout.setVerticalGroup(
            frKonvolusiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frKonvolusiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btConvBack)
                .addContainerGap())
        );

        jLabel10.setText("Morphology");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btMorpDilation.setText("Dilation");
        btMorpDilation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMorpDilationActionPerformed(evt);
            }
        });

        btMorpErotion.setText("Erosion");
        btMorpErotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMorpErotionActionPerformed(evt);
            }
        });

        btClosing.setText("Closing");
        btClosing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClosingActionPerformed(evt);
            }
        });

        btOpening.setText("Opening");
        btOpening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpeningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btMorpDilation)
                        .addGap(18, 18, 18)
                        .addComponent(btClosing, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btMorpErotion)
                        .addGap(18, 18, 18)
                        .addComponent(btOpening, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMorpDilation)
                    .addComponent(btClosing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMorpErotion)
                    .addComponent(btOpening))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btMorpBack.setText("Back");
        btMorpBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMorpBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frMorphologyLayout = new javax.swing.GroupLayout(frMorphology.getContentPane());
        frMorphology.getContentPane().setLayout(frMorphologyLayout);
        frMorphologyLayout.setHorizontalGroup(
            frMorphologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frMorphologyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frMorphologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMorpBack)
                    .addGroup(frMorphologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frMorphologyLayout.setVerticalGroup(
            frMorphologyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frMorphologyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMorpBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Segmentation");

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btSegmenTres.setText("Treshold");
        btSegmenTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegmenTresActionPerformed(evt);
            }
        });

        valSegTres.setValue(200);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSegmenTres, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valSegTres, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSegmenTres)
                    .addComponent(valSegTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSegBack.setText("Back");
        btSegBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frSegmentLayout = new javax.swing.GroupLayout(frSegment.getContentPane());
        frSegment.getContentPane().setLayout(frSegmentLayout);
        frSegmentLayout.setHorizontalGroup(
            frSegmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSegmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frSegmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSegBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frSegmentLayout.setVerticalGroup(
            frSegmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSegmentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSegBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Smoothing");

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Filter");

        btSmoothMean.setText("Mean");
        btSmoothMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSmoothMeanActionPerformed(evt);
            }
        });

        btSmoothModus.setText("Modus");
        btSmoothModus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSmoothModusActionPerformed(evt);
            }
        });

        btSmoothMedia.setText("Median");
        btSmoothMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSmoothMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btSmoothMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(btSmoothModus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSmoothMean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSmoothMean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSmoothMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSmoothModus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSmoothBack.setText("Back");
        btSmoothBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSmoothBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frSmoothingLayout = new javax.swing.GroupLayout(frSmoothing.getContentPane());
        frSmoothing.getContentPane().setLayout(frSmoothingLayout);
        frSmoothingLayout.setHorizontalGroup(
            frSmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSmoothingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frSmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frSmoothingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSmoothBack)
                .addContainerGap())
        );
        frSmoothingLayout.setVerticalGroup(
            frSmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSmoothingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSmoothBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Save");

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setText("Compression");

        btSaveLossy.setText("Lossy");
        btSaveLossy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveLossyActionPerformed(evt);
            }
        });

        btSaveLossless.setText("Lossless");
        btSaveLossless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveLosslessActionPerformed(evt);
            }
        });

        valDir.setText("jTextField1");

        jLabel16.setText("Filename");

        jLabel17.setText(".JPG");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btSaveLossy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btSaveLossless))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(valDir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSaveLossless)
                    .addComponent(btSaveLossy))
                .addContainerGap())
        );

        btSaveBack.setText("Back");
        btSaveBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frSaveLayout = new javax.swing.GroupLayout(frSave.getContentPane());
        frSave.getContentPane().setLayout(frSaveLayout);
        frSaveLayout.setHorizontalGroup(
            frSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frSaveLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frSaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSaveBack)))
                .addContainerGap())
        );
        frSaveLayout.setVerticalGroup(
            frSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveBack)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fitur.setText("Feature");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fitur)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fitur)
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btPreviewRGB.setText("Preview RGB");
        btPreviewRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreviewRGBActionPerformed(evt);
            }
        });

        btPreviewGray.setText("Preview Grayscale");
        btPreviewGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreviewGrayActionPerformed(evt);
            }
        });

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btOriginalRGB.setText("Original RGB");
        btOriginalRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOriginalRGBActionPerformed(evt);
            }
        });

        btOriginalGray.setText("Original Grayscale");
        btOriginalGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOriginalGrayActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btHistogram.setText("Histogram");
        btHistogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistogramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btPreviewGray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btPreviewRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btOriginalRGB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btOriginalGray, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btHistogram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPreviewRGB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPreviewGray)
                .addGap(25, 25, 25)
                .addComponent(btOriginalRGB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btOriginalGray)
                .addGap(38, 38, 38)
                .addComponent(btHistogram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btReset)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btGeser.setText("Move");
        btGeser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeserActionPerformed(evt);
            }
        });

        btZoom.setText("Zoom");
        btZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomActionPerformed(evt);
            }
        });

        btRotate.setText("Rotate");
        btRotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotateActionPerformed(evt);
            }
        });

        btBrightness.setText("Brightness");
        btBrightness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrightnessActionPerformed(evt);
            }
        });

        btConvolution.setText("Convolution");
        btConvolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConvolutionActionPerformed(evt);
            }
        });

        btMorphology.setText("Morphology");
        btMorphology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMorphologyActionPerformed(evt);
            }
        });

        btSegment.setText("Segmentation");
        btSegment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegmentActionPerformed(evt);
            }
        });

        btSmoothing.setText("Smoothing");
        btSmoothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSmoothingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBrightness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGeser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConvolution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMorphology, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSegment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSmoothing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGeser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btZoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRotate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBrightness)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConvolution)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMorphology)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSegment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSmoothing)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPreviewRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreviewRGBActionPerformed
        // TODO add your handling code here:                
        JFrame f = new JFrame("Preview RGB");        
        this.modifiedRGB = new PreviewIMG(this.R1, this.G1, this.B1);
        f.add(this.modifiedRGB);
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btPreviewRGBActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        frSave.setTitle("Save image");
        frSave.pack();
        frSave.setVisible(true);
    }//GEN-LAST:event_btSaveActionPerformed

    private void btPreviewGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreviewGrayActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Preview Grayscale");               
        this.modifiedGray = new PreviewIMG(this.Gray1);
        f.add(this.modifiedGray);
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btPreviewGrayActionPerformed

    private void btGeserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeserActionPerformed
        // TODO add your handling code here:
        frGeser.setTitle("Move");
        frGeser.pack();
        frGeser.setVisible(true);
    }//GEN-LAST:event_btGeserActionPerformed

    private void btKiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKiriActionPerformed
        // TODO add your handling code here:
        this.segmented = false;
        this.moveR = (int)valGeser.getValue();
        this.R1 = geser.GeserL(this.R1, this.moveR);
        this.G1 = geser.GeserL(this.G1, this.moveR);
        this.B1 = geser.GeserL(this.B1, this.moveR);
        this.Gray1 = geser.GeserL(this.Gray1, this.moveR);
        frGeser.dispose();
    }//GEN-LAST:event_btKiriActionPerformed

    private void btAtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtasActionPerformed
        // TODO add your handling code here:
        this.moveR = (int)valGeser.getValue();
        this.R1 = geser.GeserU(this.R1, this.moveR);
        this.G1 = geser.GeserU(this.G1, this.moveR);
        this.B1 = geser.GeserU(this.B1, this.moveR);
        this.Gray1 = geser.GeserU(this.Gray1, this.moveR);
        frGeser.dispose();
    }//GEN-LAST:event_btAtasActionPerformed

    private void btBawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBawahActionPerformed
        // TODO add your handling code here:
        this.moveR = (int)valGeser.getValue();
        this.R1 = geser.GeserD(this.R1, this.moveR);
        this.G1 = geser.GeserD(this.G1, this.moveR);
        this.B1 = geser.GeserD(this.B1, this.moveR);
        this.Gray1 = geser.GeserD(this.Gray1, this.moveR);
        frGeser.dispose();
    }//GEN-LAST:event_btBawahActionPerformed

    private void btKananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKananActionPerformed
        // TODO add your handling code here:
        this.moveR = (int)valGeser.getValue();        
        this.R1 = geser.GeserR(this.R1, this.moveR);
        this.G1 = geser.GeserR(this.G1, this.moveR);
        this.B1 = geser.GeserR(this.B1, this.moveR);
        this.Gray1 = geser.GeserR(this.Gray1, this.moveR);
        frGeser.dispose();
    }//GEN-LAST:event_btKananActionPerformed

    private void btZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomActionPerformed
        // TODO add your handling code here:
        frZoom.setTitle("Zoom");
        frZoom.pack();
        frZoom.setVisible(true);
    }//GEN-LAST:event_btZoomActionPerformed

    private void btRotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotateActionPerformed
        // TODO add your handling code here:
        frRotate.setTitle("Rotate");
        frRotate.pack();
        frRotate.setVisible(true);
    }//GEN-LAST:event_btRotateActionPerformed

    private void btRotateCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotateCWActionPerformed
        // TODO add your handling code here:
        this.rotateR = (int)valRotate.getValue();
        this.R1 = rotate.rotateCW(this.R1, this.rotateR);
        this.G1 = rotate.rotateCW(this.G1, this.rotateR);
        this.B1 = rotate.rotateCW(this.B1, this.rotateR);
        this.Gray1 = rotate.rotateCW(this.Gray1, this.rotateR);
        frRotate.dispose();
    }//GEN-LAST:event_btRotateCWActionPerformed

    private void btRotateCCWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotateCCWActionPerformed
        // TODO add your handling code here:
        this.rotateR = (int)valRotate.getValue();
        this.R1 = rotate.rotateCCW(this.R1, this.rotateR);
        this.G1 = rotate.rotateCCW(this.G1, this.rotateR);
        this.B1 = rotate.rotateCCW(this.B1, this.rotateR);
        this.Gray1 = rotate.rotateCCW(this.Gray1, this.rotateR);
        frRotate.dispose();
    }//GEN-LAST:event_btRotateCCWActionPerformed

    private void btOriginalRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOriginalRGBActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Preview Original RGB");        
        f.add(this.originalRGB);
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btOriginalRGBActionPerformed

    private void btOriginalGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOriginalGrayActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Preview Original Grayscale");        
        f.add(this.originalGray);
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btOriginalGrayActionPerformed

    private void btBrightnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightnessActionPerformed
        // TODO add your handling code here:
        frBrightness.setTitle("Brightness");
        frBrightness.pack();
        frBrightness.setVisible(true);
    }//GEN-LAST:event_btBrightnessActionPerformed

    private void btBrightnessIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightnessIncActionPerformed
        // TODO add your handling code here:
        this.brightnessR = (int)valBrightness.getValue();
        this.R1 = brightness1.BrightnessInc(this.R1, this.brightnessR);
        this.G1 = brightness1.BrightnessInc(this.G1, this.brightnessR);
        this.B1 = brightness1.BrightnessInc(this.B1, this.brightnessR);
        this.Gray1 = brightness1.BrightnessInc(this.Gray1, this.brightnessR);
        frBrightness.dispose();
    }//GEN-LAST:event_btBrightnessIncActionPerformed

    private void btBrightnessDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightnessDecActionPerformed
        // TODO add your handling code here:
        this.brightnessR = (int)valBrightness.getValue();
        this.R1 = brightness1.BrightnessDec(this.R1, this.brightnessR);
        this.G1 = brightness1.BrightnessDec(this.G1, this.brightnessR);
        this.B1 = brightness1.BrightnessDec(this.B1, this.brightnessR);
        this.Gray1 = brightness1.BrightnessDec(this.Gray1, this.brightnessR);
        frBrightness.dispose();
    }//GEN-LAST:event_btBrightnessDecActionPerformed

    private void btBrightnessMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightnessMultActionPerformed
        // TODO add your handling code here:
        this.brightnessR = (int)valBrightness.getValue();
        this.R1 = brightness2.BrightnessMult(this.R1, this.brightnessR);
        this.G1 = brightness2.BrightnessMult(this.G1, this.brightnessR);
        this.B1 = brightness2.BrightnessMult(this.B1, this.brightnessR);
        this.Gray1 = brightness2.BrightnessMult(this.Gray1, this.brightnessR);
        frBrightness.dispose();
    }//GEN-LAST:event_btBrightnessMultActionPerformed

    private void btBrightnessDivdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightnessDivdActionPerformed
        // TODO add your handling code here:
        this.brightnessR = (int)valBrightness.getValue();
        this.R1 = brightness2.BrightnessDivd(this.R1, this.brightnessR);
        this.G1 = brightness2.BrightnessDivd(this.G1, this.brightnessR);
        this.B1 = brightness2.BrightnessDivd(this.B1, this.brightnessR);
        this.Gray1 = brightness2.BrightnessDivd(this.Gray1, this.brightnessR);
        frBrightness.dispose();
    }//GEN-LAST:event_btBrightnessDivdActionPerformed

    private void btZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomInActionPerformed
        // TODO add your handling code here:
        this.R1 = zoom.zoomIn(this.R1, 1);
        this.G1 = zoom.zoomIn(this.G1, 1);
        this.B1 = zoom.zoomIn(this.B1, 1);
        this.Gray1 = zoom.zoomIn(this.Gray1, 1);
        frZoom.dispose();
    }//GEN-LAST:event_btZoomInActionPerformed

    private void btZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomOutActionPerformed
        // TODO add your handling code here:
        this.R1 = zoom.zoomOut(this.R1, 1);
        this.G1 = zoom.zoomOut(this.G1, 1);
        this.B1 = zoom.zoomOut(this.B1, 1);
        this.Gray1 = zoom.zoomOut(this.Gray1, 1);
        frZoom.dispose();
    }//GEN-LAST:event_btZoomOutActionPerformed

    private void btHistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistogramActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Histogram Equalization RGB");
        this.histogram = new Histogram(this.R1, this.G1, this.B1, this.Gray1);
        f.add(new PreviewIMG(this.histogram.getImgHist()));
        f.pack();        
        f.setVisible(true);        
        
//        JFrame fg = new JFrame("Histogram Equalization Gray");
//        fg.add(new PreviewIMG(this.histogram.histEqGray()));
//        fg.pack();        
//        fg.setVisible(true);        
    }//GEN-LAST:event_btHistogramActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        this.segmented = false;
        this.R1 = this.R;
        this.G1 = this.G;
        this.B1 = this.B;
        this.Gray1 = this.Gray;
    }//GEN-LAST:event_btResetActionPerformed

    private void btConvolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvolutionActionPerformed
        // TODO add your handling code here:
        frKonvolusi.setTitle("Brightness");
        frKonvolusi.pack();
        frKonvolusi.setVisible(true);
    }//GEN-LAST:event_btConvolutionActionPerformed

    private void btConvSharpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvSharpenActionPerformed
        // TODO add your handling code here:
        this.R1 = konvolusi.konvolusiResul(this.R1, Sharpen.getKernel());
        this.G1 = konvolusi.konvolusiResul(this.G1, Sharpen.getKernel());
        this.B1 = konvolusi.konvolusiResul(this.B1, Sharpen.getKernel());
        this.Gray1 = konvolusi.konvolusiResul(this.Gray1, Sharpen.getKernel());        
        frKonvolusi.dispose();
    }//GEN-LAST:event_btConvSharpenActionPerformed

    private void btConvEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvEdgeActionPerformed
        // TODO add your handling code here:
        this.R1 = konvolusi.konvolusiResul(this.R1, Edge.getKernel());
        this.G1 = konvolusi.konvolusiResul(this.G1, Edge.getKernel());
        this.B1 = konvolusi.konvolusiResul(this.B1, Edge.getKernel());
        this.Gray1 = konvolusi.konvolusiResul(this.Gray1, Edge.getKernel());        
        frKonvolusi.dispose();
    }//GEN-LAST:event_btConvEdgeActionPerformed

    private void btConvBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConvBackActionPerformed
        // TODO add your handling code here:
        frKonvolusi.dispose();
    }//GEN-LAST:event_btConvBackActionPerformed

    private void btBrightBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrightBackActionPerformed
        // TODO add your handling code here:
        frBrightness.dispose();
    }//GEN-LAST:event_btBrightBackActionPerformed

    private void btRotateBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotateBackActionPerformed
        // TODO add your handling code here:
        frRotate.dispose();
    }//GEN-LAST:event_btRotateBackActionPerformed

    private void btZoomBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomBackActionPerformed
        // TODO add your handling code here:
        frZoom.dispose();
    }//GEN-LAST:event_btZoomBackActionPerformed

    private void btGeserBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeserBackActionPerformed
        // TODO add your handling code here:
        frGeser.dispose();
    }//GEN-LAST:event_btGeserBackActionPerformed

    private void btMorphologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMorphologyActionPerformed
        // TODO add your handling code here:
        frMorphology.setTitle("Moprhology");
        frMorphology.pack();
        frMorphology.setVisible(true);
    }//GEN-LAST:event_btMorphologyActionPerformed

    private void btMorpBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMorpBackActionPerformed
        // TODO add your handling code here:
        frMorphology.dispose();
    }//GEN-LAST:event_btMorpBackActionPerformed

    private void btMorpDilationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMorpDilationActionPerformed
        // TODO add your handling code here:
        if(!this.segmented)imgTresholdRun();
        imgDilation();
        frMorphology.dispose();
    }//GEN-LAST:event_btMorpDilationActionPerformed

    private void btMorpErotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMorpErotionActionPerformed
        // TODO add your handling code here:
        if(!this.segmented)imgTresholdRun();
        imgErosion();
        frMorphology.dispose();
    }//GEN-LAST:event_btMorpErotionActionPerformed

    private void btSegmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegmentActionPerformed
        // TODO add your handling code here:
        frSegment.setTitle("Segmentation");
        frSegment.pack();
        frSegment.setVisible(true);
    }//GEN-LAST:event_btSegmentActionPerformed

    private void btSegBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegBackActionPerformed
        // TODO add your handling code here:
        frSegment.dispose();
    }//GEN-LAST:event_btSegBackActionPerformed

    private void btSegmenTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegmenTresActionPerformed
        // TODO add your handling code here:
        imgTresholdRun();
        frSegment.dispose();
    }//GEN-LAST:event_btSegmenTresActionPerformed

    private void btSmoothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSmoothingActionPerformed
        // TODO add your handling code here:
        frSmoothing.setTitle("Smoothing");
        frSmoothing.pack();
        frSmoothing.setVisible(true);
    }//GEN-LAST:event_btSmoothingActionPerformed

    private void btSmoothBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSmoothBackActionPerformed
        // TODO add your handling code here:
        frSmoothing.dispose();
    }//GEN-LAST:event_btSmoothBackActionPerformed

    private void btSmoothMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSmoothMeanActionPerformed
        // TODO add your handling code here:
        this.R1 = smoothaf.smoothMean(this.R1);
        this.G1 = smoothaf.smoothMean(this.G1);
        this.B1 = smoothaf.smoothMean(this.B1);
        this.Gray1 = smoothaf.smoothMean(this.Gray1);
        frSmoothing.dispose();
    }//GEN-LAST:event_btSmoothMeanActionPerformed

    private void btSmoothMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSmoothMediaActionPerformed
        // TODO add your handling code here:
        this.R1 = smoothaf.smoothMedian(this.R1);
        this.G1 = smoothaf.smoothMedian(this.G1);
        this.B1 = smoothaf.smoothMedian(this.B1);
        this.Gray1 = smoothaf.smoothMedian(this.Gray1);
        frSmoothing.dispose();
    }//GEN-LAST:event_btSmoothMediaActionPerformed

    private void btSmoothModusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSmoothModusActionPerformed
        // TODO add your handling code here:
        this.R1 = smoothaf.smoothModus(this.R1);
        this.G1 = smoothaf.smoothModus(this.G1);
        this.B1 = smoothaf.smoothModus(this.B1);
        this.Gray1 = smoothaf.smoothModus(this.Gray1);
        frSmoothing.dispose();
    }//GEN-LAST:event_btSmoothModusActionPerformed

    private void btClosingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClosingActionPerformed
        // TODO add your handling code here:
        if(!this.segmented)imgTresholdRun();
        imgDilation();
        imgErosion();
        frMorphology.dispose();
    }//GEN-LAST:event_btClosingActionPerformed

    private void btOpeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpeningActionPerformed
        // TODO add your handling code here:
        if(!this.segmented)imgTresholdRun();
        imgErosion();
        imgDilation();
        frMorphology.dispose();
    }//GEN-LAST:event_btOpeningActionPerformed

    private void btSaveBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveBackActionPerformed
        // TODO add your handling code here:
        frSave.dispose();
    }//GEN-LAST:event_btSaveBackActionPerformed

    private void btSaveLossyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveLossyActionPerformed
        // TODO add your handling code here:
        Lossy saveLossy = new Lossy(this.R1, this.G1, this.B1, this.Gray1, this.valDir.getText());
        try {
            saveLossy.save();
            System.out.println("Success");
        } catch (IOException ex) {
            System.out.println("Fail to save");
            Logger.getLogger(EditFieldView.class.getName()).log(Level.SEVERE, null, ex);
        }
        frSave.dispose();
        
    }//GEN-LAST:event_btSaveLossyActionPerformed

    private void btSaveLosslessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveLosslessActionPerformed
        // TODO add your handling code here:
        Lossless saveLossless = new Lossless(this. R1, this.G1, this.B1, this.Gray1, this.valDir.getText());
        try {
            saveLossless.save();
            System.out.println("Success");
        } catch (IOException ex) {
            System.out.println("Fail to save");
            Logger.getLogger(EditFieldView.class.getName()).log(Level.SEVERE, null, ex);
        }
        frSave.dispose();
    }//GEN-LAST:event_btSaveLosslessActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditFieldView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditFieldView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditFieldView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditFieldView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditFieldView().setVisible(true);
//            }
//        });
//    }
    
    Geser geser = new Geser();
    Zoom zoom = new Zoom();
    Rotate rotate = new Rotate();
    Brightness1 brightness1 = new Brightness1();
    Brightness2 brightness2 = new Brightness2();
    Histogram histogram;
    Konvolusi konvolusi = new Konvolusi();
    Sharpening Sharpen = new Sharpening();
    EdgeDetection Edge = new EdgeDetection();
    Erosi erosi = new Erosi();
    Dilasi dilasi = new Dilasi();
    SegmentasiThreshold SegTreshold = new SegmentasiThreshold();
    Smoothing smoothaf = new Smoothing();
    
    private int[][] R, G, B, Gray;
    private int[][] R1, G1, B1, Gray1;
    private int brightnessR, rotateR, moveR;
    private PreviewIMG originalRGB, originalGray, modifiedRGB, modifiedGray;
    private BufferedImage img;
    private boolean segmented;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtas;
    private javax.swing.JButton btBawah;
    private javax.swing.JButton btBrightBack;
    private javax.swing.JButton btBrightness;
    private javax.swing.JButton btBrightnessDec;
    private javax.swing.JButton btBrightnessDivd;
    private javax.swing.JButton btBrightnessInc;
    private javax.swing.JButton btBrightnessMult;
    private javax.swing.JButton btClosing;
    private javax.swing.JButton btConvBack;
    private javax.swing.JButton btConvEdge;
    private javax.swing.JButton btConvSharpen;
    private javax.swing.JButton btConvolution;
    private javax.swing.JButton btGeser;
    private javax.swing.JButton btGeserBack;
    private javax.swing.JButton btHistogram;
    private javax.swing.JButton btKanan;
    private javax.swing.JButton btKiri;
    private javax.swing.JButton btMorpBack;
    private javax.swing.JButton btMorpDilation;
    private javax.swing.JButton btMorpErotion;
    private javax.swing.JButton btMorphology;
    private javax.swing.JButton btOpening;
    private javax.swing.JButton btOriginalGray;
    private javax.swing.JButton btOriginalRGB;
    private javax.swing.JButton btPreviewGray;
    private javax.swing.JButton btPreviewRGB;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btRotate;
    private javax.swing.JButton btRotateBack;
    private javax.swing.JButton btRotateCCW;
    private javax.swing.JButton btRotateCW;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSaveBack;
    private javax.swing.JButton btSaveLossless;
    private javax.swing.JButton btSaveLossy;
    private javax.swing.JButton btSegBack;
    private javax.swing.JButton btSegmenTres;
    private javax.swing.JButton btSegment;
    private javax.swing.JButton btSmoothBack;
    private javax.swing.JButton btSmoothMean;
    private javax.swing.JButton btSmoothMedia;
    private javax.swing.JButton btSmoothModus;
    private javax.swing.JButton btSmoothing;
    private javax.swing.JButton btZoom;
    private javax.swing.JButton btZoomBack;
    private javax.swing.JButton btZoomIn;
    private javax.swing.JButton btZoomOut;
    private javax.swing.JLabel fitur;
    private javax.swing.JFrame frBrightness;
    private javax.swing.JFrame frGeser;
    private javax.swing.JFrame frKonvolusi;
    private javax.swing.JFrame frMorphology;
    private javax.swing.JFrame frRotate;
    private javax.swing.JFrame frSave;
    private javax.swing.JFrame frSegment;
    private javax.swing.JFrame frSmoothing;
    private javax.swing.JFrame frZoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSpinner valBrightness;
    private javax.swing.JTextField valDir;
    private javax.swing.JSpinner valGeser;
    private javax.swing.JSpinner valRotate;
    private javax.swing.JSpinner valSegTres;
    // End of variables declaration//GEN-END:variables

    public void addListener(EditField aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
